### ISSUE TITLE
JSHint

### ISSUE THREAD

**Issue by JTronLabs** [rblopes/phaser-plus-template#5]
I think it'd be helpful to have JSHint directives in these template files. They're ES6 and using a text-editor linter is best practice.

Include `/* jshint esversion: 6 */` at the top of each generated file.

**Comment by JTronLabs** [comment]
People can use different linters, but JSHint is the most popular. It's also easier to be forced to change the linter name than it is to have to remember to add it in.

**Comment by rblopes** [comment]
Sorry, what's the editor/plugin you are using? Wouldn't it be the case of changing your settings then?

**Comment by JTronLabs** [comment]
I am using [Atom](https://atom.io/) with the [linter](https://atom.io/packages/linter) and [JSHint packages](https://atom.io/packages/linter-jshint). After some more research it looks like this template uses ESLint and is configured via `.eslintrc`. 

Sorry for all the trash issues, just  trying to help! I appreciate your fast responses and excellent knowledge.

**Comment by JTronLabs** [comment]
But seriously, this project has taught me a TON about Phaser, JS dev, best practices etc. Thank you! Just trying to give back.

**Comment by rblopes** [comment]
Thanks.
